[project]
name = "inventory-manager-business-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sunday OYENIYI", email = "sunday.oyeniyi6@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cryptography>=50.0.0",
    "django>=6.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.0",
    "drf-spectacular>=0.30.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.4",
    "python-dotenv>=1.2.3",
    "python-jose>=3.5.0",
    "python-keycloak>=7.1.1",
]

[project.scripts]
inventory-manager-business-core = "inventory_manager_business_core:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
