# Generated by Django 6.1 on 2026-08-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='encrypted_keycloak_client_secret',
            field=models.BinaryField(blank=True, help_text='Secret chiffré du client backend', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='keycloak_client_id',
            field=models.CharField(blank=True, help_text='Client ID du backend dans le realm du tenant', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='keycloak_realm_name',
            field=models.CharField(blank=True, help_text='Nom du realm dans Keycloak', max_length=255, null=True, unique=True),
        ),
    ]
