# Generated by Django 6.1 on 2026-08-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de taxe par défaut en pourcentage (ex: 18.00 pour 18%)', max_digits=5),
        ),
    ]
